/**
 * ICARUS v5.0 - Módulos Index
 *
 * Lista completa dos 58 módulos do sistema com metadados.
 * Use este arquivo como referência central para todos os módulos.
 */

export interface ModuleMetadata {
  id: number
  name: string
  displayName: string
  category: string
  description: string
  route: string
  icon: string
  status: 'completed' | 'development' | 'planned'
  priority: 'high' | 'medium' | 'low'
  phase: 1 | 2 | 3 | 4
}

export const ICARUS_MODULES: ModuleMetadata[] = [
  // ASSISTENCIAL (15 módulos)
  {
    id: 1,
    name: 'AtendimentoAmbulatorial',
    displayName: 'Atendimento Ambulatorial',
    category: 'Assistencial',
    description: 'Consultas e retornos ambulatoriais',
    route: '/assistencial/ambulatorial',
    icon: 'Stethoscope',
    status: 'planned',
    priority: 'high',
    phase: 1,
  },
  {
    id: 2,
    name: 'ProntoSocorro',
    displayName: 'Pronto Socorro',
    category: 'Assistencial',
    description: 'Emergências e urgências',
    route: '/assistencial/pronto-socorro',
    icon: 'Ambulance',
    status: 'planned',
    priority: 'high',
    phase: 1,
  },
  {
    id: 3,
    name: 'Internacao',
    displayName: 'Internação',
    category: 'Assistencial',
    description: 'Gestão de leitos e internações',
    route: '/assistencial/internacao',
    icon: 'Bed',
    status: 'planned',
    priority: 'high',
    phase: 1,
  },
  {
    id: 4,
    name: 'CentroCirurgico',
    displayName: 'Centro Cirúrgico',
    category: 'Assistencial',
    description: 'Agendamento e controle de cirurgias',
    route: '/assistencial/centro-cirurgico',
    icon: 'Scissors',
    status: 'planned',
    priority: 'high',
    phase: 1,
  },
  {
    id: 5,
    name: 'UTICTI',
    displayName: 'UTI/CTI',
    category: 'Assistencial',
    description: 'Gestão de terapia intensiva',
    route: '/assistencial/uti',
    icon: 'HeartPulse',
    status: 'planned',
    priority: 'high',
    phase: 2,
  },
  {
    id: 6,
    name: 'Laboratorio',
    displayName: 'Laboratório',
    category: 'Assistencial',
    description: 'Exames laboratoriais',
    route: '/assistencial/laboratorio',
    icon: 'TestTube',
    status: 'planned',
    priority: 'high',
    phase: 1,
  },
  {
    id: 7,
    name: 'ImagemDiagnostico',
    displayName: 'Imagem e Diagnóstico',
    category: 'Assistencial',
    description: 'Radiologia, tomografia, ressonância',
    route: '/assistencial/imagem',
    icon: 'Scan',
    status: 'planned',
    priority: 'medium',
    phase: 2,
  },
  {
    id: 8,
    name: 'FarmaciaHospitalar',
    displayName: 'Farmácia Hospitalar',
    category: 'Assistencial',
    description: 'Dispensação e controle de medicamentos',
    route: '/assistencial/farmacia',
    icon: 'Pill',
    status: 'planned',
    priority: 'medium',
    phase: 2,
  },
  {
    id: 9,
    name: 'Hemoterapia',
    displayName: 'Hemoterapia',
    category: 'Assistencial',
    description: 'Banco de sangue',
    route: '/assistencial/hemoterapia',
    icon: 'Droplet',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },
  {
    id: 10,
    name: 'Radioterapia',
    displayName: 'Radioterapia',
    category: 'Assistencial',
    description: 'Tratamentos oncológicos',
    route: '/assistencial/radioterapia',
    icon: 'Radiation',
    status: 'planned',
    priority: 'low',
    phase: 4,
  },
  {
    id: 11,
    name: 'Quimioterapia',
    displayName: 'Quimioterapia',
    category: 'Assistencial',
    description: 'Protocolos e aplicações',
    route: '/assistencial/quimioterapia',
    icon: 'Syringe',
    status: 'planned',
    priority: 'low',
    phase: 4,
  },
  {
    id: 12,
    name: 'Fisioterapia',
    displayName: 'Fisioterapia',
    category: 'Assistencial',
    description: 'Sessões e evolução',
    route: '/assistencial/fisioterapia',
    icon: 'Dumbbell',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },
  {
    id: 13,
    name: 'Nutricao',
    displayName: 'Nutrição',
    category: 'Assistencial',
    description: 'Dietas e acompanhamento',
    route: '/assistencial/nutricao',
    icon: 'Apple',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },
  {
    id: 14,
    name: 'Enfermagem',
    displayName: 'Enfermagem',
    category: 'Assistencial',
    description: 'Prescrições e evolução de enfermagem',
    route: '/assistencial/enfermagem',
    icon: 'Cross',
    status: 'planned',
    priority: 'high',
    phase: 2,
  },
  {
    id: 15,
    name: 'ProntuarioEletronico',
    displayName: 'Prontuário Eletrônico',
    category: 'Assistencial',
    description: 'PEP completo',
    route: '/assistencial/prontuario',
    icon: 'FileText',
    status: 'completed',
    priority: 'high',
    phase: 1,
  },

  // ADMINISTRATIVO (10 módulos)
  {
    id: 16,
    name: 'Agendamento',
    displayName: 'Agendamento',
    category: 'Administrativo',
    description: 'Consultas e exames',
    route: '/administrativo/agendamento',
    icon: 'Calendar',
    status: 'planned',
    priority: 'high',
    phase: 1,
  },
  {
    id: 17,
    name: 'Faturamento',
    displayName: 'Faturamento',
    category: 'Financeiro',
    description: 'Convênios e particular',
    route: '/financeiro/faturamento',
    icon: 'FileText',
    status: 'development',
    priority: 'high',
    phase: 2,
  },
  {
    id: 18,
    name: 'Recepcao',
    displayName: 'Recepção',
    category: 'Administrativo',
    description: 'Check-in e check-out',
    route: '/administrativo/recepcao',
    icon: 'DoorOpen',
    status: 'planned',
    priority: 'high',
    phase: 2,
  },
  {
    id: 19,
    name: 'AuditoriaMedica',
    displayName: 'Auditoria Médica',
    category: 'Administrativo',
    description: 'Glosas e análises',
    route: '/administrativo/auditoria',
    icon: 'Search',
    status: 'planned',
    priority: 'medium',
    phase: 2,
  },
  {
    id: 20,
    name: 'Ouvidoria',
    displayName: 'Ouvidoria',
    category: 'Administrativo',
    description: 'SAC e reclamações',
    route: '/administrativo/ouvidoria',
    icon: 'MessageSquare',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },
  {
    id: 21,
    name: 'HotelariaHospitalar',
    displayName: 'Hotelaria Hospitalar',
    category: 'Administrativo',
    description: 'Conforto e amenidades',
    route: '/administrativo/hotelaria',
    icon: 'Hotel',
    status: 'planned',
    priority: 'low',
    phase: 4,
  },
  {
    id: 22,
    name: 'Transporte',
    displayName: 'Transporte',
    category: 'Administrativo',
    description: 'Ambulâncias e remoções',
    route: '/administrativo/transporte',
    icon: 'Car',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },
  {
    id: 23,
    name: 'Manutencao',
    displayName: 'Manutenção',
    category: 'Administrativo',
    description: 'Predial e equipamentos',
    route: '/administrativo/manutencao',
    icon: 'Wrench',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },
  {
    id: 24,
    name: 'CentralLeitos',
    displayName: 'Central de Leitos',
    category: 'Administrativo',
    description: 'Regulação de leitos',
    route: '/administrativo/central-leitos',
    icon: 'BedDouble',
    status: 'planned',
    priority: 'high',
    phase: 2,
  },
  {
    id: 25,
    name: 'Cadastros',
    displayName: 'Cadastros',
    category: 'Administrativo',
    description: 'Pacientes, convênios, médicos',
    route: '/administrativo/cadastros',
    icon: 'Database',
    status: 'planned',
    priority: 'high',
    phase: 1,
  },

  // FINANCEIRO (8 módulos)
  {
    id: 26,
    name: 'ContasPagar',
    displayName: 'Contas a Pagar',
    category: 'Financeiro',
    description: 'Gestão de fornecedores',
    route: '/financeiro/contas-pagar',
    icon: 'CreditCard',
    status: 'planned',
    priority: 'high',
    phase: 2,
  },
  {
    id: 27,
    name: 'ContasReceber',
    displayName: 'Contas a Receber',
    category: 'Financeiro',
    description: 'Convênios e pacientes',
    route: '/financeiro/contas-receber',
    icon: 'Receipt',
    status: 'planned',
    priority: 'high',
    phase: 2,
  },
  {
    id: 28,
    name: 'FluxoCaixa',
    displayName: 'Fluxo de Caixa',
    category: 'Financeiro',
    description: 'Tesouraria',
    route: '/financeiro/fluxo-caixa',
    icon: 'Wallet',
    status: 'planned',
    priority: 'high',
    phase: 2,
  },
  {
    id: 29,
    name: 'FaturamentoTISS',
    displayName: 'Faturamento TISS',
    category: 'Financeiro',
    description: 'Padrão ANS',
    route: '/financeiro/tiss',
    icon: 'FileCheck',
    status: 'planned',
    priority: 'high',
    phase: 2,
  },
  {
    id: 30,
    name: 'Glosas',
    displayName: 'Glosas',
    category: 'Financeiro',
    description: 'Gestão de negativas',
    route: '/financeiro/glosas',
    icon: 'AlertCircle',
    status: 'planned',
    priority: 'high',
    phase: 2,
  },
  {
    id: 31,
    name: 'Contratos',
    displayName: 'Contratos',
    category: 'Financeiro',
    description: 'Convênios e fornecedores',
    route: '/financeiro/contratos',
    icon: 'FileSignature',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },
  {
    id: 32,
    name: 'CustosHospitalares',
    displayName: 'Custos Hospitalares',
    category: 'Financeiro',
    description: 'ABC e rateio',
    route: '/financeiro/custos',
    icon: 'Calculator',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },
  {
    id: 33,
    name: 'Orcamento',
    displayName: 'Orçamento',
    category: 'Financeiro',
    description: 'Planejamento financeiro',
    route: '/financeiro/orcamento',
    icon: 'PiggyBank',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },

  // SUPRIMENTOS (8 módulos)
  {
    id: 34,
    name: 'Produtos',
    displayName: 'Produtos',
    category: 'Suprimentos',
    description: 'Catálogo de produtos',
    route: '/suprimentos/produtos',
    icon: 'Package',
    status: 'completed',
    priority: 'high',
    phase: 3,
  },
  {
    id: 35,
    name: 'Compras',
    displayName: 'Compras',
    category: 'Suprimentos',
    description: 'Cotações e pedidos',
    route: '/suprimentos/compras',
    icon: 'ShoppingCart',
    status: 'development',
    priority: 'high',
    phase: 3,
  },
  {
    id: 36,
    name: 'Estoque',
    displayName: 'Estoque',
    category: 'Suprimentos',
    description: 'Movimentações',
    route: '/suprimentos/estoque',
    icon: 'Box',
    status: 'planned',
    priority: 'high',
    phase: 3,
  },
  {
    id: 37,
    name: 'Almoxarifado',
    displayName: 'Almoxarifado',
    category: 'Suprimentos',
    description: 'Materiais',
    route: '/suprimentos/almoxarifado',
    icon: 'Warehouse',
    status: 'planned',
    priority: 'high',
    phase: 3,
  },
  {
    id: 38,
    name: 'Patrimonio',
    displayName: 'Patrimônio',
    category: 'Suprimentos',
    description: 'Bens e equipamentos',
    route: '/suprimentos/patrimonio',
    icon: 'Building',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },
  {
    id: 39,
    name: 'Fornecedores',
    displayName: 'Fornecedores',
    category: 'Suprimentos',
    description: 'Cadastro e avaliação',
    route: '/suprimentos/fornecedores',
    icon: 'Truck',
    status: 'planned',
    priority: 'high',
    phase: 3,
  },
  {
    id: 40,
    name: 'Requisicoes',
    displayName: 'Requisições',
    category: 'Suprimentos',
    description: 'Solicitações internas',
    route: '/suprimentos/requisicoes',
    icon: 'ClipboardList',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },
  {
    id: 41,
    name: 'Inventario',
    displayName: 'Inventário',
    category: 'Suprimentos',
    description: 'Contagens e ajustes',
    route: '/suprimentos/inventario',
    icon: 'ListChecks',
    status: 'planned',
    priority: 'medium',
    phase: 4,
  },

  // RECURSOS HUMANOS (7 módulos)
  {
    id: 42,
    name: 'Colaboradores',
    displayName: 'Colaboradores',
    category: 'Recursos Humanos',
    description: 'Cadastro e dados',
    route: '/rh/colaboradores',
    icon: 'Users',
    status: 'development',
    priority: 'high',
    phase: 2,
  },
  {
    id: 43,
    name: 'PontoEletronico',
    displayName: 'Ponto Eletrônico',
    category: 'Recursos Humanos',
    description: 'Controle de jornada',
    route: '/rh/ponto',
    icon: 'Clock',
    status: 'planned',
    priority: 'high',
    phase: 2,
  },
  {
    id: 44,
    name: 'FolhaPagamento',
    displayName: 'Folha de Pagamento',
    category: 'Recursos Humanos',
    description: 'Processamento',
    route: '/rh/folha',
    icon: 'DollarSign',
    status: 'planned',
    priority: 'high',
    phase: 2,
  },
  {
    id: 45,
    name: 'Escalas',
    displayName: 'Escalas',
    category: 'Recursos Humanos',
    description: 'Plantões e turnos',
    route: '/rh/escalas',
    icon: 'CalendarDays',
    status: 'planned',
    priority: 'high',
    phase: 2,
  },
  {
    id: 46,
    name: 'Treinamentos',
    displayName: 'Treinamentos',
    category: 'Recursos Humanos',
    description: 'Capacitações',
    route: '/rh/treinamentos',
    icon: 'GraduationCap',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },
  {
    id: 47,
    name: 'AvaliacaoDesempenho',
    displayName: 'Avaliação de Desempenho',
    category: 'Recursos Humanos',
    description: 'Gestão por competências',
    route: '/rh/avaliacao',
    icon: 'Star',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },
  {
    id: 48,
    name: 'Beneficios',
    displayName: 'Benefícios',
    category: 'Recursos Humanos',
    description: 'VT, VR, plano de saúde',
    route: '/rh/beneficios',
    icon: 'Gift',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },

  // QUALIDADE E REGULATÓRIO (5 módulos)
  {
    id: 49,
    name: 'Indicadores',
    displayName: 'Indicadores',
    category: 'Qualidade',
    description: 'KPIs e metas',
    route: '/qualidade/indicadores',
    icon: 'BarChart',
    status: 'planned',
    priority: 'high',
    phase: 2,
  },
  {
    id: 50,
    name: 'Acreditacao',
    displayName: 'Acreditação',
    category: 'Qualidade',
    description: 'ONA, JCI',
    route: '/qualidade/acreditacao',
    icon: 'Award',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },
  {
    id: 51,
    name: 'CCIH',
    displayName: 'CCIH',
    category: 'Qualidade',
    description: 'Controle de infecção',
    route: '/qualidade/ccih',
    icon: 'Shield',
    status: 'planned',
    priority: 'high',
    phase: 2,
  },
  {
    id: 52,
    name: 'Farmacovigilancia',
    displayName: 'Farmacovigilância',
    category: 'Qualidade',
    description: 'Eventos adversos',
    route: '/qualidade/farmacovigilancia',
    icon: 'AlertTriangle',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },
  {
    id: 53,
    name: 'Comissoes',
    displayName: 'Comissões',
    category: 'Qualidade',
    description: 'Prontuários, óbitos, ética',
    route: '/qualidade/comissoes',
    icon: 'Users',
    status: 'planned',
    priority: 'medium',
    phase: 4,
  },

  // ANALYTICS E BI (5 módulos)
  {
    id: 54,
    name: 'DashboardExecutivo',
    displayName: 'Dashboard Executivo',
    category: 'Analytics',
    description: 'Visão geral',
    route: '/analytics/dashboard',
    icon: 'LayoutDashboard',
    status: 'development',
    priority: 'high',
    phase: 1,
  },
  {
    id: 55,
    name: 'RelatoriosGerenciais',
    displayName: 'Relatórios Gerenciais',
    category: 'Analytics',
    description: 'Consolidados',
    route: '/analytics/relatorios',
    icon: 'FileBarChart',
    status: 'planned',
    priority: 'high',
    phase: 2,
  },
  {
    id: 56,
    name: 'AnalisePreditiva',
    displayName: 'Análise Preditiva',
    category: 'Analytics',
    description: 'IA e Machine Learning',
    route: '/analytics/preditiva',
    icon: 'Brain',
    status: 'planned',
    priority: 'high',
    phase: 2,
  },
  {
    id: 57,
    name: 'Benchmarking',
    displayName: 'Benchmarking',
    category: 'Analytics',
    description: 'Comparações',
    route: '/analytics/benchmarking',
    icon: 'TrendingUp',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },
  {
    id: 58,
    name: 'BusinessIntelligence',
    displayName: 'Business Intelligence',
    category: 'Analytics',
    description: 'Cubos e análises',
    route: '/analytics/bi',
    icon: 'Database',
    status: 'planned',
    priority: 'medium',
    phase: 3,
  },
]

// Helpers
export const getModuleByName = (name: string) =>
  ICARUS_MODULES.find((m) => m.name === name)

export const getModulesByCategory = (category: string) =>
  ICARUS_MODULES.filter((m) => m.category === category)

export const getModulesByStatus = (status: ModuleMetadata['status']) =>
  ICARUS_MODULES.filter((m) => m.status === status)

export const getModulesByPhase = (phase: number) =>
  ICARUS_MODULES.filter((m) => m.phase === phase)

export const categories = [...new Set(ICARUS_MODULES.map((m) => m.category))]

export const stats = {
  total: ICARUS_MODULES.length,
  completed: ICARUS_MODULES.filter((m) => m.status === 'completed').length,
  development: ICARUS_MODULES.filter((m) => m.status === 'development').length,
  planned: ICARUS_MODULES.filter((m) => m.status === 'planned').length,
}
